### ISSUE TITLE
请问楼主的loading动画是原创的吗？

### ISSUE THREAD

**Issue by huangzhike** [rocky-191/baseTemplate#1]
如题，这是楼主的页面https://rocky-191.github.io/baseTemplate/cssLoading.html
之前曾经在一个外国人的Github看过，现在找不到了，但是现在找到几个很像的页面
http://d.lanrentuku.com/down/js/qita-1191/
http://demo.lanrenzhijia.com/2015/load0409/

**Comment by rocky-191** [comment]
不是，从别人那里借鉴写的。写在这里就是整理下，万一别人的找不到可以用这个
